# ******************************************************************************
# * Project:  CMake4GDAL
# * Purpose:  CMake build scripts
# * Author: Hiroshi Miura
# ******************************************************************************
# * Copyright (C) 2017,2018 Hiroshi Miura
# *
# * Permission is hereby granted, free of charge, to any person obtaining a
# * copy of this software and associated documentation files (the "Software"),
# * to deal in the Software without restriction, including without limitation
# * the rights to use, copy, modify, merge, publish, distribute, sublicense,
# * and/or sell copies of the Software, and to permit persons to whom the
# * Software is furnished to do so, subject to the following conditions:
# *
# * The above copyright notice and this permission notice shall be included
# * in all copies or substantial portions of the Software.
# *
# * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# * DEALINGS IN THE SOFTWARE.
# ******************************************************************************

## for debug
#SET(CMAKE_BUILD_TYPE "Debug" CACHE STRING "")
#SET(CMAKE_RULE_MESSAGES OFF CACHE BOOL "")
#SET(CMAKE_VERBOSE_MAKEFILE ON CACHE BOOL "")

#DRIVERS
SET(GDAL_ENABLE_FRMT_ADRG ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_AIGRID ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_AAIGRID ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_AIRSAR ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_ARG ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_BMP ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_BSB ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_CALS ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_CEOS ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_CEOS2 ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_COASP ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_COSAR ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_CTG ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_DDS ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_DIMAP ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_DODS ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_DTED ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_E00GRID ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_ECW ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_EEDA ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_ELAS ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_ENVISAT ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_EPSILON ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_FIT ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_FITS ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_GIF ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_GTA ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_GFF ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_GIF ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_GRIB ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_GSG ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_GTA ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_GTIFF ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_GXF ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_HDF4 ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_HDF5 ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_HF2 ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_HFA ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_IDRISI ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_ILWIS ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_INGR ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_IRIS ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_JAXAPALSAR ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_JDEM ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_JPEG ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_JPEG2000 ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_JPEGLS ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_KMLSUPEROVERLAY ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_KEA ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_L1B ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_LEVELLER ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_MAP ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_MBTILES ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_MEM ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_MRF ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_MRSID ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_MRSID_LIDAR ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_MSGN ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_NETCDF ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_NGSGEOID ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_NITF ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_OPENJPEG ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_OZI ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_PCIDSK ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_PCRASTER ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_POSTGISRASTER ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_PDF ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_PDS ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_PLMOSAIC ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_PNG ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_POSTGISRASTER ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_PRF ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_R ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_RAW ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_RASTERLITE ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_RDA ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_RIK ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_RMF ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_RS2 ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_SAFE ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_SAGA ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_SDTS ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_SENTINEL2 ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_SGI ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_TERRAGEN ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_TIL ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_TSX ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_USGSDEM ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_VRT ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_WCS ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_WEBP ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_WMS ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_WMTS ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_XPM ON CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_XYZ ON CACHE BOOL "")


SET(OGR_ENABLE_AMIGOCLOUD ON CACHE BOOL "")
SET(OGR_ENABLE_CAD ON CACHE BOOL "")
SET(OGR_ENABLE_CARTO ON CACHE BOOL "")
SET(OGR_ENABLE_CLOUDANT ON CACHE BOOL "")
SET(OGR_ENABLE_CSW ON CACHE BOOL "")
SET(OGR_ENABLE_DODS ON CACHE BOOL "")
SET(OGR_ENABLE_ELASTIC ON CACHE BOOL "")
SET(OGR_ENABLE_GEOJSON ON CACHE BOOL "")
SET(OGR_ENABLE_GEOMEDIA ON CACHE BOOL "")
SET(OGR_ENABLE_GFT ON CACHE BOOL "")
SET(OGR_ENABLE_GMLAS ON CACHE BOOL "")
SET(OGR_ENABLE_IDRISI ON CACHE BOOL "")
SET(OGR_ENABLE_ILI ON CACHE BOOL "")
SET(OGR_ENABLE_LIBKML ON CACHE BOOL "")
SET(OGR_ENABLE_MITAB ON CACHE BOOL "")
SET(OGR_ENABLE_MONGODB OFF CACHE BOOL "")
SET(OGR_ENABLE_MYSQL ON CACHE BOOL "")
SET(OGR_ENABLE_MVT ON CACHE BOOL "")
SET(OGR_ENABLE_NAS ON CACHE BOOL "")
SET(OGR_ENABLE_ODS ON CACHE BOOL "")
SET(OGR_ENABLE_OGDI ON CACHE BOOL "")
SET(OGR_ENABLE_OSM ON CACHE BOOL "")
SET(OGR_ENABLE_PDS ON CACHE BOOL "")
SET(OGR_ENABLE_PG ON CACHE BOOL "")
SET(OGR_ENABLE_PLSCENES ON CACHE BOOL "")
SET(OGR_ENABLE_SOSI ON CACHE BOOL "")
SET(OGR_ENABLE_SHAPE ON CACHE BOOL "")
SET(OGR_ENABLE_SQLITE ON CACHE BOOL "")
SET(OGR_ENABLE_SVG ON CACHE BOOL "")
SET(OGR_ENABLE_VFK ON CACHE BOOL "")
SET(OGR_ENABLE_WFS ON CACHE BOOL "")
SET(OGR_ENABLE_XLSX ON CACHE BOOL "")

SET(GDAL_ENABLE_QHULL ON CACHE BOOL "")

# Proprietary drivers
SET(GDAL_ENABLE_FRMT_GEORASTER OFF CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_SDE OFF CACHE BOOL "")
SET(GDAL_ENABLE_FRMT_RASDAMAN OFF CACHE BOOL "")
SET(OGR_ENABLE_SDE OFF CACHE BOOL "")
SET(OGR_ENABLE_FME OFF CACHE BOOL "")
SET(OGR_ENABLE_OCI OFF CACHE BOOL "")
SET(OGR_ENABLE_DB2 OFF CACHE BOOL "")
SET(OGR_ENABLE_DWG OFF CACHE BOOL "")
SET(OGR_ENABLE_MSSQLSPATIAL ON CACHE BOOL "")

# GRASS drivers
SET(GDAL_ENABLE_FRMT_GRASS OFF CACHE BOOL "")
SET(OGR_ENABLE_GRASS OFF CACHE BOOL "")

# BUNDLED LIBRARIES
SET(GDAL_USE_QHULL_INTERNAL ON CACHE BOOL "")
SET(GDAL_USE_LIBPCIDSK_INTERNAL ON CACHE BOOL "")
SET(GDAL_USE_LIBCSF_INTERNAL ON CACHE BOOL "")
SET(GDAL_USE_OPENCAD_INTERNAL ON CACHE BOOL "")
SET(GDAL_USE_LIBLERC_INTERNAL ON CACHE BOOL "")
set(GDAL_USE_LIBGEOTIFF_INTERNAL ON CACHE BOOL "")
