steps:
- task: docker@1
  displayName: Build docker image
  inputs:
    command: build
    imageName: ${{ parameters.imageName }}
    dockerFile: $(Build.SourcesDirectory)/ci/azure-pipelines/${{ parameters.dockerFile }}
    volumes: |
      $(Build.SourcesDirectory):/src
      $(Build.BinariesDirectory):/build
    envVars: ${{ parameters.environmentVariables }}
- task: docker@1
  displayName: Build and test gdal
  inputs:
    command: run
    imageName: ${{ parameters.imageName }}
    volumes: |
      $(Build.SourcesDirectory):/src
      $(Build.BinariesDirectory):/build
    envVars: ${{ parameters.environmentVariables }}
    containerCommand: /src/ci/azure-pipelines/${{parameters.scriptFile}}
    runInBackground: false
