steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
- bash: |
    git clone https://github.com/osgeo/gdal.git
    ln -s $(Build.SourcesDirectory) $(Build.BinariesDirectory)/gdal/cmake4gdal
    python $(Build.BinariesDirectory)/gdal/cmake4gdal/deploy.py
    mkdir build
  workingDirectory: '$(Build.BinariesDirectory)'
- task: CMake@1
  displayName: configure gdal
  inputs:
    workingDirectory: '$(Build.BinariesDirectory)/build'
    cmakeArgs: -DCMAKE_BUILD_TYPE=Debug ${{parameters.CMAKE_OPTIONS}} -C${{parameters.CONFIGURATIONS}} $(Build.BinariesDirectory)/gdal
- task: Cmake@1
  displayName: build gdal
  inputs:
    cmakeArgs: --build $(Build.BinariesDirectory)/build
- task: CMake@1
  displayName: run quicktest
  inputs:
    cmakeArgs: --build $(Build.BinariesDirectory)/build --target quicktest
- task: CMake@1
  displayName: run autotest
  inputs:
    cmakeArgs: --build $(Build.BinariesDirectory)/build --target autotest
