
function(list_filter_exclude _list_name _value)
    if(CMAKE_VERSION VERSION_LESS 3.12)
        list(FIND ${_list_name}  ${_value} _INDEX)
        if(${_INDEX} GREATER -1)
            list(REMOVE_AT ${_list_name} ${_INDEX})
        endif()
    else()
        list(FILTER ${_list_name} EXCLUDE REGEX ${_value})
    endif()
    set(${_list_name} ${${_list_name}} PARENT_SCOPE)
endfunction()
