
set(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_CXX_COMPILER i686-w64-mingw32-g++)
set(CMAKE_C_COMPILER i686-w64-mingw32-gcc)
set(CMAKE_RC_COMPILER i686-w64-mingw32-windres)

set(CMAKE_CROSSCOMPILING_EMULATOR
    /usr/bin/env WINEPATH=${CMAKE_BINARY_DIR}/gdal wine
    CACHE PATH "")

set(CMAKE_CXX_COMPILER_LAUNCHER ccache)
set(CMAKE_C_COMPILER_LAUNCHER ccache)

set(CMAKE_FIND_ROOT_PATH  /usr/i686-w64-mingw32/)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
